### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by kopasz9** [daboynb/PlayIntegrityNEXT#6]
Hi i do everything what is here . But still not working .🙄

**Comment by daboynb** [comment]
Currently all the custom rom are not working.  Are you using one?

**Comment by kopasz9** [comment]
Yes I using thé namless rom.
But the oldest version is worked for me. But now no. Use thé fingeeprint downloader app.
And Its worked fine. But now not working.

**Comment by daboynb** [comment]
You need to wait for the dev to sign the rom and update.

**Comment by kopasz9** [comment]
Okay. Thank you 😊

**Comment by kopasz9** [comment]
Hi. Can i ask you with which Custom rom now it work???

**Comment by daboynb** [comment]
You need to ask the developer who made the ROM, as the maintainers are not the same for every device.

The only one I know for certain that is signed is LineageOS.
