### ISSUE TITLE
Please give us the fp Downloader back

### ISSUE THREAD

**Issue by Benjamin2389** [daboynb/PlayIntegrityNEXT#7]
The module now checks every 30 minutes wether your fp is still working.
Today I was in a store and my fingerprint got banned unknown to the app.
I was able to solve it using termux which still works.
Before it was great the module changed fp every 6 hours and in case it was necessary you had the app.
I would really love to see that being changed like it was before.
It is a great module thank you for working on it but the last update made it worse so please roll it back or make it optional

Mfg

**Comment by daboynb** [comment]
The app checks every 6 hours.. the new scripts every 30 mins... so the app  it's worse..... btw i'll make again the apk and upload in a separate folder on this repo

**Comment by daboynb** [comment]
https://github.com/daboynb/PlayIntegrityNEXT/tree/main/apk
